### ISSUE TITLE
Community missing

### ISSUE THREAD

**Issue by Ilovegym66** [92lleo/ioBroker.freifunk#1]
Hi, great job yet! 
I know, early state, the config page is very good!
I miss my freifunk-darmstadt community, set one time München, but can t delete it any more..

**Comment by 92lleo** [comment]
Hi, thanks for the feedback! 
Communities are hardcoded for testing currently, plan is to fetch them from the freifunk API. I plan to get it done until end of this week, i'll update the issue then
(the only nodes you will see until then are my own😄)

**Comment by Ilovegym66** [comment]
Fine 😁👍

**Comment by 92lleo** [comment]
You may try the current revision. You still can't select a community, but you can use https://meshviewer.darmstadt.freifunk.net/data/nodelist.json as "nodelist url" for darmstadt. then add filters for name(s) (or parts of names, case-insensitive) and/or id(s)

**Comment by Ilovegym66** [comment]
Hi, works fine for me, thank you!

**Comment by 92lleo** [comment]
Great! I'll leave this open until the community selection is working

**Comment by 92lleo** [comment]
@Ilovegym66 one year later... but community selection is now working for communities using "nodelist" for advertising their nodes. More fixes/features coming

**Comment by Ilovegym66** [comment]
Hi, thank you, but I must dispose my router... I have no freifunk any more in the moment..
But it can be that I start a new one with this projekt in the near future.

**Comment by 92lleo** [comment]
Oh okay, no problem!
Closing this.
